services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=https://codebaserag.hashirayaz.site/api
      # - VITE_API_URL=http://143.110.183.231:3000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - CHROMA_DB_URL=http://chromadb:8000 # Backend connects to ChromaDB
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redisredis619
    depends_on:
      - chromadb
      - redis

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    environment:
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["http://143.110.183.231:3000","http://backend:3000"]

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data


volumes:
  caddy_data:
  caddy_config:
  redis_data:
