
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://143.110.183.231:3000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - CHROMA_DB_URL=http://chromadb:8000 # Backend connects to ChromaDB
    depends_on:
      - chromadb

  chromadb:
    image: chromadb/chromadb:latest
    ports:
      - "8000:8000"
    environment:
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS='["http://143.110.183.231:3000"]'
